# Generated by Django 5.0 on 2024-01-12 23:03

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(null=True, upload_to=posts.models.upload_to),
        ),
    ]
